### ISSUE TITLE
Euler solver - missing integration timepoints

### ISSUE THREAD

**Issue by cagatayyildiz** [juntang-zhuang/torch_ACA#3]
Hi!

Thanks for your paper and nicely written code! I'm having issues with the Euler solver. Here is my code sample and respective errors:

```
H = 50
ts = 0.1 * torch.arange(H+1,dtype=torch.float32)
options = {}
options.update({'method': 'Euler'})
options.update({'h': 0.01})
options.update({'t0': ts.tolist()[0]})
options.update({'t1': ts.tolist()[-1]})
options.update({'t_eval':ts.tolist()})
st = odesolve(odef, s0, options) # s0 is [N,n] & st is [49,N,n]
```
When I print the `t` input in my `odef` function, it prints up until `4.98`, which I guess explains why `st` is `[49,N,n]`. But I believe `st` should have been `[51,N,n]`. What do you think?

Also, this integration yields `Evaluation points outside integration range. Please re-specify t0 and t1 s.t. t0 < t_eval < t1 or t1 < t_eval < t0 STRICTLY, and use a FINER grid.` error/warning. Should I set, e.g., `options.update({'t1': ts.tolist()[-1]+1e-8})`?

Thanks,
Cagatay.

**Comment by juntang-zhuang** [comment]
Hi, thanks for the feedback. Yes you should set t1 as larger value than you actually want, perhaps should use t1+h as the ending time. This is because the integration steps is defined by (t1-t0)/h. However, in the code I used something like int(abs(t1 - t0)/h) (or rounding to integer), and I did not check if it takes the last step, but use t1+h should solve this.

**Comment by cagatayyildiz** [comment]
I already tried that but I guess something strange is going on. I still get `Evaluation points outside integration range. Please re-specify t0 and t1 s.t. t0 < t_eval < t1 or t1 < t_eval < t0 STRICTLY, and use a FINER grid.` warning when I set the options as follows:

```  
print(options['t0'])
print(options['t1'])
print(options['t_eval'])

# outputs
# -0.01
# 5.01
# [0.0, 0.10000000149011612, 0.20000000298023224, 0.30000001192092896, 0.4000000059604645, 0.5, 0.6000000238418579, 0.699999988079071, 0.800000011920929, 0.9000000357627869, 1.0, 1.100000023841858, 1.2000000476837158, 1.3000000715255737, 1.399999976158142, 1.5, 1.600000023841858, 1.7000000476837158, 1.8000000715255737, 1.899999976158142, 2.0, 2.1000001430511475, 2.200000047683716, 2.299999952316284, 2.4000000953674316, 2.5, 2.6000001430511475, 2.700000047683716, 2.799999952316284, 2.9000000953674316, 3.0, 3.1000001430511475, 3.200000047683716, 3.299999952316284, 3.4000000953674316, 3.5, 3.6000001430511475, 3.700000047683716, 3.799999952316284, 3.9000000953674316, 4.0, 4.099999904632568, 4.200000286102295, 4.300000190734863, 4.400000095367432, 4.5, 4.599999904632568, 4.700000286102295, 4.800000190734863, 4.900000095367432, 5.0]

```

**Comment by juntang-zhuang** [comment]
Just updated the code, see commit here https://github.com/juntang-zhuang/torch_ACA/commit/4ddc106bf7e99d39b9b0c1ccf39f6560222e28c3.
Also provide a test code ```test_euler.py```.
The grid is shifted by one-step, and fixed by define steps as [(n+1)*h+t0 for n in range(Nt)]. 
The previous evaluation range is t_eval \in [a,b), now changed to t_eval \in [a,b].

**Comment by cagatayyildiz** [comment]
Thanks for the update! I'm now using the following options and still get the error `Evaluation points outside integration range. Please re-specify t0 and t1 s.t. t0 < t_eval < t1 or t1 < t_eval < t0 STRICTLY, and use a FINER grid.`

```
{'method': 'RK4', 't0': -0.0002, 't1': 1.0001, 'h': 0.01, 't_eval': [0.0, 0.10000000149011612, 0.20000000298023224, 0.30000001192092896, 0.4000000059604645, 0.5, 0.6000000238418579, 0.699999988079071, 0.800000011920929, 0.9000000357627869, 1.0]}
```

Update: When I set the options as follows, then the error goes away. 
```
    options.update({'t0': ts[0].item() - step_size})
    options.update({'t1': ts[-1].item() + step_size})
    options.update({'t_eval': ts.tolist()})
```

I still find it a little strange that we input `t0` and `t1`  as well as `t_eval`, which alone implies what `t0` and `t1` are.
